import EmployeeTable from "./EmployeeTable";

const employees = [
  {
    firstName: "Sandra",
    lastName: "Williams",
    gender: "Female",
    employeeID: "EMP001",
    phoneNumber: "08130000001",
    role: "Admin",
    department: "Human Resources",
  },
  {
    firstName: "Abubakar",
    lastName: "Ibrahim",
    gender: "Male",
    employeeID: "EMP002",
    phoneNumber: "07062000033",
    role: "IT",
    department: "Operations",
  },
  {
    firstName: "Ikechukwu",
    lastName: "Ugbonna",
    gender: "Male",
    employeeID: "EMP003",
    phoneNumber: "08130000002",
    role: "IT",
    department: "Operations",
  },
  {
    firstName: "Joshua",
    lastName: "Adewale",
    gender: "Male",
    employeeID: "EMP004",
    phoneNumber: "07038126632",
    role: "Admin",
    department: "Project Management",
  },
  {
    firstName: "Fatimah",
    lastName: "Nasir",
    gender: "Female",
    employeeID: "EMP005",
    phoneNumber: "08130000003",
    role: "Admin",
    department: "Customer Service",
  },
  {
    firstName: "Hauwa",
    lastName: "Lateef",
    gender: "Female",
    employeeID: "EMP006",
    phoneNumber: "08130000004",
    role: "IT",
    department: "Human Resources",
  },
  {
    firstName: "Sunday",
    lastName: "Allison",
    gender: "Male",
    employeeID: "EMP007",
    phoneNumber: "08130000005",
    role: "Admin",
    department: "Finance",
  },
  {
    firstName: "Ngozi",
    lastName: "Okafor",
    gender: "Female",
    employeeID: "EMP008",
    phoneNumber: "08130000006",
    role: "HR",
    department: "Recruitment",
  },
  {
    firstName: "Mohammed",
    lastName: "Ali",
    gender: "Male",
    employeeID: "EMP009",
    phoneNumber: "08130000007",
    role: "IT",
    department: "Development",
  },
  {
    firstName: "Maryam",
    lastName: "Bello",
    gender: "Female",
    employeeID: "EMP010",
    phoneNumber: "08130000008",
    role: "Admin",
    department: "Administration",
  },
  {
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    employeeID: "EMP011",
    phoneNumber: "08130000009",
    role: "IT",
    department: "Network",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    gender: "Female",
    employeeID: "EMP012",
    phoneNumber: "08130000010",
    role: "Admin",
    department: "Customer Relations",
  },
  {
    firstName: "Aisha",
    lastName: "Mohammed",
    gender: "Female",
    employeeID: "EMP013",
    phoneNumber: "08130000011",
    role: "HR",
    department: "Training",
  },
  {
    firstName: "David",
    lastName: "Jones",
    gender: "Male",
    employeeID: "EMP014",
    phoneNumber: "08130000012",
    role: "IT",
    department: "Development",
  },
  {
    firstName: "Amaka",
    lastName: "Eze",
    gender: "Female",
    employeeID: "EMP015",
    phoneNumber: "08130000013",
    role: "HR",
    department: "Compensation",
  },
  {
    firstName: "Chinwe",
    lastName: "Okeke",
    gender: "Female",
    employeeID: "EMP016",
    phoneNumber: "08130000014",
    role: "Admin",
    department: "Procurement",
  },
  {
    firstName: "Peter",
    lastName: "Clement",
    gender: "Male",
    employeeID: "EMP017",
    phoneNumber: "08130000015",
    role: "Admin",
    department: "Logistics",
  },
  {
    firstName: "Sarah",
    lastName: "Paul",
    gender: "Female",
    employeeID: "EMP018",
    phoneNumber: "08130000016",
    role: "IT",
    department: "Support",
  },
  {
    firstName: "Emeka",
    lastName: "Nwosu",
    gender: "Male",
    employeeID: "EMP019",
    phoneNumber: "08130000017",
    role: "HR",
    department: "Recruitment",
  },
  {
    firstName: "Binta",
    lastName: "Abdullahi",
    gender: "Female",
    employeeID: "EMP020",
    phoneNumber: "08130000018",
    role: "Admin",
    department: "Finance",
  },
];

export default function Employee() {
  return <EmployeeTable employees={employees} />;
}
